version: "3.9"

services:
  notification-api:
    build: .
    container_name: notification-agorapp
    ports:
      - "8082:8082"
    environment:
      PORT: 8082
      SPRING_PROFILES_ACTIVE: default
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-*}
    restart: unless-stopped
