# Perfil para migración a Azure Database for PostgreSQL
spring.datasource.url=${AZURE_DB_URL:${DB_URL}}
spring.datasource.username=${AZURE_DB_USERNAME:${DB_USERNAME}}
spring.datasource.password=${AZURE_DB_PASSWORD:${DB_PASSWORD}}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
